name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./recommendation-and-booking/pom.xml
          mvn clean package -f ./customer-support/pom.xml
          mvn clean package -f ./partnership-management/pom.xml
          mvn clean package -f ./collaboration-management/pom.xml

      - name: Docker Build and push for RecommendationAndBooking
        uses: docker/build-push-action@v4
        with:
          context: ./recommendation-and-booking
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/recommendation-and-booking:latest
            ghcr.io/${{ github.repository }}/recommendation-and-booking:${{ github.ref_name }}
            
      - name: Docker Build and push for CustomerSupport
        uses: docker/build-push-action@v4
        with:
          context: ./customer-support
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer-support:latest
            ghcr.io/${{ github.repository }}/customer-support:${{ github.ref_name }}
            
      - name: Docker Build and push for PartnershipManagement
        uses: docker/build-push-action@v4
        with:
          context: ./partnership-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/partnership-management:latest
            ghcr.io/${{ github.repository }}/partnership-management:${{ github.ref_name }}
            
      - name: Docker Build and push for CollaborationManagement
        uses: docker/build-push-action@v4
        with:
          context: ./collaboration-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/collaboration-management:latest
            ghcr.io/${{ github.repository }}/collaboration-management:${{ github.ref_name }}
            
