apiVersion: v1
kind: Service
metadata:
  name: collaboration-management
  labels:
    app: collaboration-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: collaboration-management