apiVersion: v1
kind: Service
metadata:
  name: recommendation-and-booking
  labels:
    app: recommendation-and-booking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: recommendation-and-booking